#!/bin/bash

set -euo pipefail
set -x

readonly ROOT="$(git rev-parse --show-toplevel)"
readonly TEST_PLUGIN="${ROOT}/elm-protobuf-test"

if [[ ! -f "${TEST_PLUGIN}" ]]; then
    echo "compiled test plugin required"
    exit 1
fi

protoc \
    --proto_path=./tests/proto \
    --elm_out=./tests \
    --plugin=protoc-gen-elm="${TEST_PLUGIN}" \
    ./tests/proto/*.proto

elm-test 
